name: 'LaTeX with CMake'
description: 'Build your LaTeX using CMake'

inputs:
  input_path:
    description: 'CMake build input path'
    required: true
    default: '.'
  output_path:
    description: 'CMake build output path'
    required: true
    default: 'build'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.input_path }}
    - ${{ inputs.output_path }}

